var cards = [
  {正面: "acquisition", 反面: "收購（公司等）；獲得（物）", status: "none"},
  {正面: "affiliated company", 反面: "關係企業", status: "none"},
  {正面: "ahead of the game", 反面: "在（某領域）領先", status: "none"},
  {正面: "allocate", 反面: "分派；分配", status: "none"},
  {正面: "bankruptcy", 反面: "破產", status: "none"},
  {正面: "boast", 反面: "以……自豪", status: "none"},
  {正面: "branch office", 反面: "分公司", status: "none"},
  {正面: "branch out", 反面: "擴充（業務）", status: "none"},
  {正面: "breakthrough", 反面: "突破", status: "none"},
  {正面: "brochure", 反面: "小冊子；指南", status: "none"},
  {正面: "company profile", 反面: "公司概況", status: "none"},
  {正面: "competent", 反面: "有能力的；能勝任的", status: "none"},
  {正面: "comprehensive", 反面: "廣泛的；全面的；綜合的", status: "none"},
  {正面: "contribution", 反面: "貢獻；捐款；捐贈物", status: "none"},
  {正面: "core business", 反面: "核心事業", status: "none"},
  {正面: "corner the market", 反面: "壟斷市場", status: "none"},
  {正面: "corporation", 反面: "公司；企業", status: "none"},
  {正面: "counselor", 反面: "顧問", status: "none"},
  {正面: "cutting-edge", 反面: "尖端的；先進的", status: "none"},
  {正面: "delegate", 反面: "委派（某人）做；授（權）", status: "none"},
  {正面: "demographic", 反面: "（按性別、年齡、收入等區分的）人口統計資料；以市場作區隔的族群", status: "none"},
  {正面: "division", 反面: "事業部；部門", status: "none"},
  {正面: "dominate", 反面: "支配；在……中占主要地位", status: "none"},
  {正面: "enhancement", 反面: "（品質、清晰度等的）提高、提升", status: "none"},
  {正面: "expand", 反面: "張開；擴張", status: "none"},
  {正面: "expertise", 反面: "專業知識；專門技術", status: "none"},
  {正面: "feature", 反面: "（產品）特色；以……為特色", status: "none"},
  {正面: "found", 反面: "創立", status: "none"},
  {正面: "functionality", 反面: "功能", status: "none"},
  {正面: "high-end", 反面: "高消費階層的；迎合高層次消費者的", status: "none"},
  {正面: "in association with", 反面: "與……合作", status: "none"},
  {正面: "incorporate", 反面: "納入；併入；合併", status: "none"},
  {正面: "initiate", 反面: "發起；創始", status: "none"},
  {正面: "innovation", 反面: "創新", status: "none"},
  {正面: "integrated", 反面: "整合的", status: "none"},
  {正面: "intellectual property", 反面: "智慧財產權", status: "none"},
  {正面: "keep up with", 反面: "跟上；保持聯繫；持續學習（新事物）", status: "none"},
  {正面: "last but not least", 反面: "最後，但也同樣重要的是……", status: "none"},
  {正面: "listed company", 反面: "上市公司", status: "none"},
  {正面: "marketable", 反面: "有銷路的；暢銷的；市場的", status: "none"},
  {正面: "match sth./sb. up", 反面: "撮合；媒合", status: "none"},
  {正面: "merger", 反面: "合併", status: "none"},
  {正面: "monopoly", 反面: "獨佔；專賣；壟斷", status: "none"},
  {正面: "operation", 反面: "營運；經營", status: "none"},
  {正面: "outlook", 反面: "展望；看法；前景", status: "none"},
  {正面: "oversee", 反面: "監督；看管", status: "none"},
  {正面: "product development", 反面: "產品開發；產品研發", status: "none"},
  {正面: "prototype", 反面: "原型；標準；模範", status: "none"},
  {正面: "research and development", 反面: "研發", status: "none"},
  {正面: "resistant", 反面: "防……的；抗……的", status: "none"},
  {正面: "resource", 反面: "資源；物力", status: "none"},
  {正面: "slogan", 反面: "標語；宣傳口號", status: "none"},
  {正面: "specs", 反面: "（產品）規格", status: "none"},
  {正面: "state-run enterprise", 反面: "國營企業", status: "none"},
  {正面: "stylish", 反面: "時髦的；有風格的", status: "none"},
  {正面: "subsidiary", 反面: "子公司", status: "none"},
  {正面: "task", 反面: "任務；工作；作業", status: "none"},
  {正面: "team up with", 反面: "與……合作", status: "none"},
  {正面: "underestimate", 反面: "低估", status: "none"},
  {正面: "user-friendly", 反面: "容易使用的；（設計時）考慮使用者需要的", status: "none"},

  // 61-84 補強清單 (混合練習)
  {正面: "小冊子；指南", 反面: "brochure", status: "none"},
  {正面: "公司概況", 反面: "company profile", status: "none"},
  {正面: "有能力的；能勝任的", 反面: "competent", status: "none"},
  {正面: "廣泛的；全面的；綜合的", 反面: "comprehensive", status: "none"},
  {正面: "貢獻；捐款；捐贈物", 反面: "contribution", status: "none"},
  {正面: "核心事業", 反面: "core business", status: "none"},
  {正面: "壟斷市場", 反面: "corner the market", status: "none"},
  {正面: "公司；企業", 反面: "corporation", status: "none"},
  {正面: "顧問", 反面: "counselor", status: "none"},
  {正面: "尖端的；先進的", 反面: "cutting-edge", status: "none"},
  {正面: "委派（某人）做；授（權）", 反面: "delegate", status: "none"},
  {正面: "（按性別、年齡、收入等區分的）人口統計資料；以市場作區隔的族群", 反面: "demographic", status: "none"},
  {正面: "事業部；部門", 反面: "division", status: "none"},
  {正面: "支配；在……中占主要地位", 反面: "dominate", status: "none"},
  {正面: "納入；併入；合併", 反面: "incorporate", status: "none"},
  {正面: "發起；創始", 反面: "initiate", status: "none"},
  {正面: "創新", 反面: "innovation", status: "none"},
  {正面: "整合的", 反面: "integrated", status: "none"},
  {正面: "智慧財產權", 反面: "intellectual property", status: "none"},
  {正面: "國營企業", 反面: "state-run enterprise", status: "none"},
  {正面: "時髦的；有風格的", 反面: "stylish", status: "none"},
  {正面: "子公司", 反面: "subsidiary", status: "none"},
  {正面: "任務；工作；作業", 反面: "task", status: "none"},
  {正面: "與……合作", 反面: "team up with", status: "none"}
];